version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: syr
    volumes:
      - .:/app
      - /app/node_modules
    # Set environment variables if needed
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: ${DATABASE_URL}
    # Start in dev mode
    restart: always
