version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: syr
    volumes:
      - .:/app
      # Avoid overwriting node_modules with an empty folder
      - /app/node_modules
    # Set environment variables if needed
    environment:
      # If you're on Windows or certain environments, you may need polling:
      # CHOKIDAR_USEPOLLING: "true"
      NEXT_TELEMETRY_DISABLED: "1"
    # Start in dev mode
    command: npm run dev
    restart: always
